---
before_script:
  - docker info

stages:
- build
- deploy

build_image:
  stage: build
  tags:
  - container-builder
  script:
  - docker build -t edoburu/python-runner:base base/
  - docker build -t edoburu/python-runner:ansible ansible/
  - docker build -t edoburu/python-runner:sphinx sphinx/
  - docker build -t edoburu/python-runner:wkhtmltopdf wkhtmltopdf/
  - docker tag edoburu/python-runner:base edoburu/python-runner:latest

push_image:
  stage: deploy
  tags:
  - container-builder
  script:
  - docker login
  - docker push edoburu/python-runner:base
  - docker push edoburu/python-runner:latest
  - docker push edoburu/python-runner:sphinx
  - docker push edoburu/python-runner:ansible
  - docker push edoburu/python-runner:wkhtmltopdf
